language: node_js

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - yarn build

after_success:
  - firebase deploy --token=${FIREBASE_TOKEN}
